
services:

  backend:
    build:
      context: ./backend
      dockerfile: cloud-dev.dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8080"
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cloud-dev-123
    ports:
      - "5432:5432"

  database-editor:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api-editor:
    image: esperotech/yaade
    restart: always
    environment:
      YAADE_ADMIN_USERNAME: admin
    volumes:
      - ./backend/yaade:/app/data
    ports:
      - "9339:9339"

  frontend:
    image: nginx
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"